name: Update Share Links

on:
  push:
    paths:
      - "*.scripting"   # 只监听新增或修改的 .scripting 文件
    branches:
      - main
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate links and update README
        run: node scripts/update_links.js

      - name: Commit changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto update share links" || echo "No changes"
          git push
